### PR TITLE
Added note to configure webpack option

### PR DESCRIPTION
**Pull request by hitautodestruct**
Added a message stating that you should manipulate the config object and then return it.

### CODE REVIEW

**Comment by egoist** [comment]
actually it's optional, you don't need to return it

**Comment by hitautodestruct** [comment]
What if I manipulate it?

**Comment by hitautodestruct** [comment]
@egoist adding a plugin and then not returning the configuration doesn't do anything 🙃

**Comment by egoist** [comment]
it does, e.g. `config.plugins.push` will mutate the original object

**Comment by hitautodestruct** [comment]
Ok, then how about I add an example of mutating and optionally returning
the config?

**Comment by egoist** [comment]
there's already a note: https://github.com/hitautodestruct/website/blame/2a4f2cd0534c90b2dcb0349c4214999188eb3d47/docs/guide/update-webpack-config.md#L26 😄

**Comment by hitautodestruct** [comment]
Sure, I saw that.

But I had to go the docs and figure it out. Could save someone a few
minutes if there was a practical example.

That's what I was aiming for.
I can change the warning to either an example or a tip.

**Comment by egoist** [comment]
looking good, we don't use semicolon tho 😄

**Comment by hitautodestruct** [comment]
> looking good, we don't use semicolon tho 😄

Neither do I 😆

**Pull request merged**
